spring.application.name=Sorokin_Event
spring.datasource.url=jdbc:postgresql://localhost:5432/sorokin
spring.datasource.username=sorokin
spring.datasource.password=user
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

springdoc.swagger-ui.url: /openapi.yaml